name: Dispatch

on:
  push:
    branches:
      - main

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        run: |
          curl -X POST \
            -H "Authorization: token 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" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            "https://api.github.com/repos/sonigeez/Salsim/dispatches" \
            --data '{"event_type": "update_submodule"}'
